import crypto from "node:crypto";
import { createSsoSession, type SsoSession } from "../sso-client.js";

// --- Types ---

export type TokenResponse = {
  access_token: string;
  token_type: string;
  expires_in: number;
  refresh_token?: string;
  id_token?: string;
  scope?: string;
};

export type UserInfo = {
  sub: string;
  name?: string;
  email?: string;
  email_verified?: boolean;
  [key: string]: unknown;
};

export type CallbackResult = {
  user: UserInfo;
  accessToken: string;
};

// --- Config helpers ---

function getSsoBaseUrl(): string {
  return process.env.SSO_URL ?? "http://localhost:8848";
}

// --- Service-account SSO session ---

/**
 * Lazy singleton：首次使用时用环境变量中的服务账号凭据登录 SSO，
 * 后续所有对 SSO 服务器的请求通过此会话发出（自动携带 JSESSIONID）。
 */
let _ssoSession: SsoSession | null = null;

function getSsoSession(): SsoSession {
  if (!_ssoSession) {
    const username = process.env.SSO_SERVICE_USERNAME;
    const password = process.env.SSO_SERVICE_PASSWORD;
    if (!username || !password) {
      throw new Error(
        "SSO_SERVICE_USERNAME / SSO_SERVICE_PASSWORD 未配置，无法建立 SSO 服务账号会话",
      );
    }
    _ssoSession = createSsoSession(username, password, getSsoBaseUrl());
  }
  return _ssoSession;
}

export function getFrontendUrl(): string {
  return process.env.FRONTEND_URL ?? "http://localhost:5173";
}

function getClientId(): string {
  const id = process.env.SSO_CLIENT_ID;
  if (!id) throw new Error("SSO_CLIENT_ID is not configured");
  return id;
}

function getClientSecret(): string {
  const secret = process.env.SSO_CLIENT_SECRET;
  if (!secret) throw new Error("SSO_CLIENT_SECRET is not configured");
  return secret;
}

/**
 * The redirect_uri used in the authorization request.
 * Must point to the cocow-web frontend so the browser lands there with ?code=.
 */
function getRedirectUri(): string {
  return process.env.SSO_REDIRECT_URI ?? `${getFrontendUrl()}/login/callback`;
}

// --- Core SSO service functions ---

/**
 * Build the OAuth 2 / OIDC authorization URL for the SSO server.
 * The state must be generated by the caller and stored (e.g. in sessionStorage)
 * so it can be verified when the code comes back.
 */
export function buildAuthorizationUrl(state: string): string {
  const params = new URLSearchParams({
    response_type: "code",
    client_id: getClientId(),
    redirect_uri: getRedirectUri(),
    scope: "openid profile email",
    state,
  });
  // Authorize endpoint is on the SSO *frontend* (Vue SPA), not the backend API
  const ssoFrontendUrl = process.env.SSO_FRONTEND_URL ?? getSsoBaseUrl();
  return `${ssoFrontendUrl}/oauth/authorize?${params.toString()}`;
}

/**
 * Exchange an authorization code for an access token and immediately fetch
 * the user's profile from the SSO userinfo endpoint.
 * Both calls go directly from cocow-api to sso-server (localhost:8848).
 */
export async function handleCallbackCode(
  code: string,
): Promise<CallbackResult> {
  // 1. Exchange code → token
  const body = new URLSearchParams({
    grant_type: "authorization_code",
    code,
    redirect_uri: getRedirectUri(),
    client_id: getClientId(),
    client_secret: getClientSecret(),
  });

  const session = getSsoSession();

  const tokenRes = await session.fetch(
    `${getSsoBaseUrl()}/api/v1/oauth/token`,
    {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: body.toString(),
    },
  );

  if (!tokenRes.ok) {
    const text = await tokenRes.text();
    throw new Error(`Token exchange failed (${tokenRes.status}): ${text}`);
  }

  const tokenData = (await tokenRes.json()) as { accessToken: string };
  const accessToken = tokenData.accessToken;

  // 2. Fetch user info
  const userRes = await session.fetch(
    `${getSsoBaseUrl()}/api/v1/oauth/userinfo`,
    {
      headers: { Authorization: `Bearer ${accessToken}` },
    },
  );

  if (!userRes.ok) {
    const text = await userRes.text();
    throw new Error(`Userinfo request failed (${userRes.status}): ${text}`);
  }

  const user = (await userRes.json()) as UserInfo;
  return { user, accessToken };
}
