import type { Request, Response } from "express";
import { buildAuthorizationUrl, handleCallbackCode } from "./login.services.js";

/**
 * GET /api/v1/login/sso
 *
 * Returns the SSO authorization URL as JSON so the frontend can redirect
 * the browser there itself (preserving the state value in sessionStorage
 * for CSRF verification after the code comes back).
 *
 * Response: { url: string }
 */
export const ssoRedirect = (req: Request, res: Response) => {
  // state is generated by the frontend and stored in sessionStorage;
  // we accept it as a query param so we can embed it in the URL.
  const state = (req.query.state as string | undefined) ?? "";
  const url = buildAuthorizationUrl(state);
  res.json({ url });
};

/**
 * POST /api/v1/login/callback
 *
 * Called by the cocow-web frontend after it receives ?code=&state= from the
 * SSO server redirect.  The frontend has already verified the CSRF state;
 * this endpoint exchanges the code for a token and fetches the user profile
 * entirely server-side so the client_secret never reaches the browser.
 *
 * The access token is stored in an HttpOnly cookie — JS cannot read it.
 *
 * Body: { code: string }
 * Response: { user: UserInfo }
 */
export const ssoCallbackPost = async (req: Request, res: Response) => {
  const { code, error, error_description } = req.body as {
    code?: string;
    error?: string;
    error_description?: string;
  };

  if (error) {
    return res
      .status(400)
      .json({ error, error_description: error_description ?? error });
  }

  if (!code || typeof code !== "string") {
    return res.status(400).json({ error: "missing_code" });
  }

  try {
    const { user, accessToken } = await handleCallbackCode(code);

    // Store the access token in an HttpOnly cookie so JS cannot read it
    res.cookie("auth_token", accessToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "strict",
      maxAge: 24 * 60 * 60 * 1000, // 24 hours
      path: "/",
    });

    return res.json({ user }); // token stays server-side
  } catch (err) {
    console.error("SSO callback error:", err);
    return res
      .status(502)
      .json({ error: "token_exchange_failed", detail: String(err) });
  }
};

/**
 * POST /api/v1/login/logout
 *
 * Clears the auth_token HttpOnly cookie.
 */
export const ssoLogout = (req: Request, res: Response) => {
  res.clearCookie("auth_token", {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "strict",
    path: "/",
  });
  res.json({ ok: true });
};
